### PR TITLE
Silence the unused typdef issues with gcc and boost

### PR DESCRIPTION
**Pull request by bilgili**

### CODE REVIEW

**Comment by bilgili** [comment]
FYI @adevress

**Comment by adevress** [comment]
Hi Ahmet,

Thank you for the commit.

The warnings related to boost are specific to boost. And they disappear by themselves with recent versions of boost and GCC.

I would prefer to not introduce not-portable GCC-specific pragma just to silent this, when it will disappear as soon as we switch to a more recent boost version.

I know you guys enforce -Werror, but simply disable it for external components if it is the source of your problem.

What do you think ?

**Comment by bilgili** [comment]
I am not seeing that happening soon ( gcc, boost upgrade ) and since it had annoyed me I decided to silence the warning.

At the same time it wont hurt other compilers if they are not giving any warnings already ?

**Comment by adevress** [comment]
> At the same time it wont hurt other compilers if they are not giving any warnings already ?

That was my fear, but it seems that even XLC handle this properly. Then let it go :)

**Pull request merged**
