### PR TITLE
Make sure Python binding cpp is not generated if not requested.

### PR DESCRIPTION
**Pull request by hernando**
Denoised CMake output.
Updated HighFive.

### CODE REVIEW

**Comment by hernando** [comment]
@ferdonline please let me know if you're happy with the changes. This is not completely blocking, but I'd like to update MVDTool in Brion to ensure both use the same version of HighFive.

**Comment by ferdonline** [comment]
Hi,
My idea with OptionRebuildSrcFile.cmake was to detect if the source pyx file was changed after the generation of the corresponding cpp file, and regenerate automatically if not. I think that would be a better solution overall.
If you agree I would prefer to fix that solution if not working in some cases before having to explicitly define a flag for building it.

**Comment by ferdonline** [comment]
Oh sorry, I see now that you use the flag set by the module. Nice!
Fine with me! Please merge

**Comment by hernando** [comment]
I'm redoing this to be simpler and behave as you expect:
- w/o Cython, use the file from the repo
- w/ Cython, generate the file everytime you build if the sources have changed (as usual).

I'm also removing the GLOB because that's a bad idea in general. The main reason is that if you add a file in your working copy but you don't touch the CMake scripts, people that pull from your repo will have an error next time they build because they haven't reconfigured. This is not only annoying for users, but it can also impact CI depending on how it's configured.

**Comment by hernando** [comment]
@adevress, I've been told Fernando is on holiday, could you please review?

**Pull request merged**
